# Generated by Django 3.0.4 on 2020-03-25 16:29

import bizzfuzz.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizzfuzz', '0004_auto_20200325_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Required. Format: YYYY-MM-DD', null=True, validators=[bizzfuzz.validators.date_max]),
        ),
    ]
